#!/bin/sh
set -e

echo "--> build"
clojure -Auberjar

echo "--> deploy"
scp target/lde.jar letsdo.events:/tmp/lde_next.jar

echo "--> restart"
ssh -tt letsdo.events 'sudo sh -c "chown lde:lde /tmp/lde_next.jar && systemctl stop lde && mv /opt/jars/lde.jar /tmp/lde_previous.jar && mv /tmp/lde_next.jar /opt/jars/lde.jar && systemctl start lde"'
